### PR TITLE
Fix #77 - Allow explicit union types on `no-explicit-generics` rule

### LINKED ISSUE #77: no-explicit-generics doesn't work correctly
version: 0.6.0

Gday,
First - great job. Thank you.

Not sure if worth removing `no-explicit-generics` from strict rule set.

 The rule is generating an error for lines of code like this...
 ```
private readonly itemSelectionUpdateSubject$ = new BehaviorSubject<ItemSelectionModel | undefined>(undefined);
```

If i follow the rule and remove the generic then when the subject is set it will error as the subject has type 'undefined'.

Maybe an option to ignore undefined could work here or probably would be better if the rule ignored generics with union types (or had an option to enable that behavior).

### PR DESCRIPTION
**Pull request by ChrisMBarr**
Now something like the following will be allowed:
```ts
const subject = new BehaviorSubject<ISomeType | null>(null);
```

This addresses #77

### CODE REVIEW

**Comment by ChrisMBarr** [comment]
Not sure I understand what the PR check failure here means, but it doesn't seem to relate to any of the changes I made

File: src/etc/is.ts [hunk 1]
```diff
@@ -144,6 +144,10 @@ export function isUnaryExpression(node: TSESTree.Node): node is TSESTree.UnaryEx
   return node.type === AST_NODE_TYPES.UnaryExpression;
 }
 
+export function isUnionType(node?: TSESTree.Node): node is TSESTree.TSUnionType {
+  return node === undefined ? false : node.type === AST_NODE_TYPES.TSUnionType;
+}
```
Comment (JasonWeinzierl) [inline src/etc/is.ts:149]:
```suggestion
export function isUnionType(node: TSESTree.Node): node is TSESTree.TSUnionType {
  return node.type === AST_NODE_TYPES.TSUnionType;
}
```

Since every other function in this file does not check for `undefined`, can we just do `typeArgs && isUnionType(typeArgs)` in the rule itself?  This would help consistency.

**Review by JasonWeinzierl — CHANGES_REQUESTED** [review]
Thank you so much!

File: src/etc/is.ts (hunk 1 above)
Comment (ChrisMBarr) [reply src/etc/is.ts:149]: I wondered about this, yeah good idea. Ill take this suggestion

**Comment by ChrisMBarr** [comment]
Do you want/need me to rebase? You can just do a rebase merge of this PR which I think would be the same in the end, right?

File: src/etc/is.ts (hunk 1 above)
Comment (JasonWeinzierl) [reply src/etc/is.ts]: (Typecheck failed because you'll need to null-check in the rule itself)

Comment (ChrisMBarr) [reply src/etc/is.ts]: Ha, yep - fixed now but the checks don't seem to be running now

**Review by JasonWeinzierl — APPROVED** [review]
